.gitignore, Guess_Game.py
=> documentation updated

Guess_Game.py
improved functionality of the code #2
=> applied int datatype

Guess_Game.py
updated with assignment operator instead of "="  #3
=> fixed syntax error

Guess_Game.py
replaced else with elif in game_guess.py
it is now fully functional #4
=> updated with fully working code

Guess_Game.py
solves random.randint now synchronised #10
=> solves random.randint now synchronised #10

Guess_Game.py
Now  if there is an wrong choice input by the user then the code again start for asking the options.
First contribution
Thank You @shivangdubey
=> Updated Guess_Game.py

receiptgenerator.py
@shivangdubey 
I have added documentation for receiptgenerator.py. Kindly merge the pull request.
=> Added documentation for receipt generator program

Guess_Game.py
Checked the type of name and improved efficiency.
=> Improved efficiency

Guess_Game.py
There was a syntax error in line 33. I resolved it
=> Debug a error

die_game.py
@shivangdubey I've added a new game. Please check and merge it.
=> Added My die Game

largest2.c
I have added a C file to calculate largest and second largest numbers among user given set of numbers.
=> I have added

fibonacci_using_dp.java
added a java code involving the concept of DP.
=> updated information

README.md, c/README.md, java/README.md, python/README.md
This PR will add README files to each language folder and also reformat the README a bit to include a Contribution statement and Code of Conduct!
I also added some descriptions for those that had them or that I could tell what they do.
=> Adds README to each folder w/ some info, Reformats README

python/castle.py
Added an interactive story mode game made using python
=> Added a python game

python/README.md, python/dinoBot.py
Dinosaur game bot written in python
=> Create dinoBot.py and README.md update

python/README.md, python/morsecode-translator.py
* Created a python program to convert morse code to english and vice versa and added it to python folder
* Added the same to readme.md file
=> Added morsecode-translator.py and made changes to readme.md

c/Prim's Algorithm.c, c/Strassen's Matrix Multiplication.c
Added a C program for Prim's Algorithm and Strassen's Matrix Multiplication. Both the algorithms are effeciently implemented using C language.
=> Prim's Algorithm and Strassen's Matrix Multiplication using C

c/Number_Guess_Game.c
I thought that it was unfair, that python folder had so many nice programs and C folder had only one so I took inspiration from Guess_Game.py and made Number_Guess_Game.c. I hope you like it.
=> Ceated a Number Guessing Game in C.

python/Unit_Converter.py
Unit Converter between metre, centimetre and inch
=> Unit Converter between metre, centimetre and inch

python/sending email.py
adding an automated email sender written in python
hope this help.
=> adding a email sending file

PseudoRandomSeriesEncrypter.py
This a highly secure encrypter which uses the pseudo random series logic. The message is encrpyted by a pseudo random series generated froma pin given. This encryoted message can be decodded again ONLY by the help of this logic using the exactly same pin.
=> Created an Encrypter using pseudo random series

README.md
Updated the current documentation to reflect the updated rules of hacktoberfest along with integration of the link with the sentence.
**Source:**
https://hacktoberfest.digitalocean.com/hacktoberfest-update
=> Hacktoberfest infomation update

python/README.md, python/simplelinearregression.py
add a simple linear regression algorithm
✌️ peace
=> Adding a linear regression algorithm project

cpp/DP Basics Using CPP/check_prime.cpp
To check whether a number is prime or not.
=> Added check_prime to cpp

python/DataFlair-Alarm-Clock.py
Making an alarm clock using python Lang.
=> Alarm Clock.py

python/KeyloggerMail.py
This can send key storks , screenshots and device info via Gmail
=> KeyloggerMail.py

c/Kruskals.c
Kruskals algorithm in C by Jacob Kuriakose
=> Kruskals algorithm in C

c++/prims.cpp
Prims algorithm in C++ by Jacob Kuriakose
=> Prims algorithm in C++ 

fibonacci.py
program to find the fibonacci series
=> fibonacci.py

c++/PATTERN.CPP
A C++ program that generates different patterns.
=> A menu-driven Pattern Program

c/Circular_queue.c
Circular queue in C by Jacob Kuriakose
=> Circular Queue in C

c/Selection_sort.c
Selection Sort in C Language by Jacob Kuriakose
=> Selection Sort in C

python/binarysearch.py
Program to perform binary search using the iterative method in python.
=> binarysearch.py

LeetCode/Java/readme.md, LeetCode/readme.md
Update the LeetCode directory readme.md to contain a description of the contents, with links to the language-specific directories within.
=> Update LeetCode readme.md

java/PrimeNumber.java
Fixed the PrimeNumber class so now it is actually working and keeps on asking you to enter number until it finds one that isn't prime.
=> Changed PrimeNumber class in java, now working. 

python/slack_message.py
Added Script will send Message to Slack Channel Added
=> Sending Message to Slack Channel (Python)

.github/workflows/greeting.yml
Greeting Github Action Workflow File added.
`It will comment on issues and to first time contributors.`
=> Create Greetings Workflow

c/Binary2decimal.c
This code converts binary cone into a decimal number.
=> Binary To decimal

python/TinderBot/Bot.py
Improve TinderBot project by asking the user to set the probability of swiping right.
=> Issue #183 adding custom swipe probabilities

python/Find no. of Upper Case Letters and Lower Case Letters.py
This is a Python Program to Calculate the Number of Upper Case Letters and Lower Case Letters in a String.
=> Find no. of Upper Case Letters and Lower Case Letters.py

python/Count the Occurrences of a Word in a Text File.py
The program takes a word from the user and counts the number of occurrences of that word in a file.
=> Count the Occurrences of a Word in a Text File.py

c++/README.md, c++/Vector-sort.cpp
Small use of c++ Template Library
=> Use of c++ Standard Template Library

python/selectionsort.py
Created a selection sort program using python.
=> Created selectionsort.py

python/Find Table Of Any Number
This is python program code which helps to find multiplication table of any number...upto any number...
This program makes easy to find multiplication table of any number and learn them or review them easily...
=> Find Table Of Any Number

python/digitalclock.py
Python program that displays real-time in a Digital clock style. Used libraries are tkinter and strftime
=> Digital Clock

python/pdf_generator/MyReport.pdf, python/pdf_generator/pdf_generator.py
This python script generates a pdf by using the generate_file pdf function which takes four arguments file name, heading, a little description and at last table data to generate table in pdf
=> issue #225 generate a pdf from data

python/README.md, python/matrixmult.py
a python program to multiply matrices using numpy in python
=> My contribution to the repository.

Array/array_advance_game.py, Array/array_intersection.py, Array/array_optimal_task.py, Array/array_plus_one.py, Array/array_stock_trading.py, Array/array_two_sum.py, Stack/stack_arr.py, Stack/stack_blncd_paranthesis.py, Stack/stack_deci_to_bin.py, Stack/stack_linkedlist.py, Stack/stack_python.py, Stack/stack_reverse_string.py
Some of the array manipulations and processing using python.
=> Array in Python

face and smile detection.py, haarcascade_frontalface_default.xml, haarcascade_smile.xml
- It is a Face and Smile Detection program which was created using OpenCV in Python.
- Haar Cascade(Machine Learning object detection algorithm) is used for identifying faces and smiles through the objects viewed from webcams.
=> Face and Smile Detector

python/Ternary_Search.py
Added ternary search in python.
This is a type of divide and conquer algorithm which divides the search space into
3 parts and finds the target value based on the property of the array or list
(usually monotonic property).
Time Complexity  : O(log3 N)
Space Complexity : O(1)
=> Ternary Search algorithm in python

java/Bogo Sort Algorithm.java
n computer science, bogo sort is a particularly ineffective sorting algorithm based on the generate and test paradigm. The algorithm successively generates permutations of its input until it finds one that is sorted. It is not useful for sorting but may be used for educational purposes, to contrast it with other more realistic algorithms.
=> Bogo Sort Algorithm.java

python/checkAnagram.py
The py code checks if two strings are anagrams eg. TRIANGLE and INTEGRAL are anagrams of each other.
=> Added python script to check if two strings are anagrams

c++/matrix_add.cpp, c/fibanocci.c
created a program on matrix addition in c++ language.
=> matrix_add.cpp

python/Qr Code Generator/qrcode.py, python/Qr Code Generator/readme.md
Qr Code Generator
This Program will help you to create a Qr code of any "Link" or "Text".
Just run the program, then a dialog box will open.
Paste the link and generate.
=> Qr Code Generator

c++/prime.cpp, c/bubblesort.c, c/matrix_add.c
created a program to add two matrices in c.
=> matrix_add.c

c++/SLL.cpp
Added basic functions used in Singly Linked Lists, implemented in C++. Precise details are commented at the top in .cpp file.
=> issue#304 Added SLL.cpp

java/RadixSort.java
=> Added Radix Sort

java/RadixSort.java
=> Addresses Issue 181

Tree traversals.cpp
added Tree traversal source code
=> create Tree traversal in cpp

c/README.md, c/SparceMatrixToTuple.c
Added c program to convert and store sparce matrix to tuple form. Also updated README.md
=> Added SparceMatixToTuple.c and Updated README.md

c/complex_num.c
created a C program to add , subtract, multiply and  divide complex numbers , complex arithmetic.
=> complex_num.c

RockPaperScisors.cpp, password_genrator.py
it is a game of rock paper scissors
=> A rock paper scissor game

c++/matrix_add.cpp
=> removed additon loop and done it parallely

python/BinarySearchTree.py
=> Adding Python Program for BST

c/SingleLinkedListManipulations.c
A C Programming code has been added to address the issue. The code contains all the required manipulations that can be performed over a Single Linked List.
=> Hacktober 2020- Basic functionalities of Single Linked List #304 Issue Resolved

c++/Given_string_is_palindrome_or_not.cpp, c++/given_string_is_palindrome_or_not.cpp
Hi Shivangdubey,
I have written an algorithm to check the given string is palindrome or not.
When we call the given string is Palindrome, First take a string "abba" now write the input string in the reverse order "abba".
Now compare the input string and output string. If both the strings are same then we call it as a Palindrome.
I first take the input string and the I am checking the first and last char of the string If both are same I will proceed else it will through output as Not a palindrome.
=> Update given string is palindrome or not.cpp

c++/Given_string_is_palindrome_or_not.cpp
Hi Shivangdubey,
I have written an algorithm to check the given string is palindrome or not.
When we call the given string is Palindrome, First take a string "abba" now write the input string in the reverse order "abba".
Now compare the input string and output string. If both the strings are same then we call it as a Palindrome.
I first take the input string and the I am checking the first and last char of the string If both are same I will proceed else it will through output as Not a palindrome.
=> String palindrome or not.cpp

python/fibonacci.py
Updated fibonacci.py to make it more user friendly.
Added a while loop and try, except statement to print an error message for invalid inputs and continue accepting inputs until the user enters an integer.
=> Updated Fibonacci.py

LeetCode/Python/string_scramble.py
Added String Scramble algorithm to LeetCode folder
=> added string scramble to LeetCode folder

LICENSE
I noticed that your project doesn't have a LICENSE, so I added the MIT license to it.
=> LICENSE added to the project

c++/DP_Basics_Using_CPP/EggDroppingProblem.cpp
You are given N floor and K eggs. You have to minimize the number of times you have to drop the eggs to find the critical floor where critical floor means the floor beyond which eggs start to break. Assumptions of the problem:
1. If egg breaks at ith floor then it also breaks at all greater floors.
2. If egg does not break at ith floor then it does not break at all lower floors.
3. Unbroken egg can be used again.
=> Uploaded Egg Dropping Problem's DP Solution

LeetCode/Python/InvertBinaryTree.py, LeetCode/Python/README.md, LeetCode/Python/RemoveElement.py, LeetCode/Python/SquaresOfSortedArray.py, LeetCode/Python/TwoCityScheduling.py
Added solutions of 5 LeetCode Problems.
=> Added some more leetcode solutions

LeetCode/Python/Longest Common Prefix.py
optimized code to find the longest common prefix string amongst an array of strings
=> Create Longest Common Prefix.py

vigenere_decryption.py, vignere_cipher.py
It includes the vigenere cipher's encryption and decryption in python.
Vignette uses simple form of polyalphabetic substitution(based on substitution using multiple alphabets.)
=> Ciphers in python

c/Airport_Simulation.c
This code will take random values of planes in the air and on the runway and then manage them accordingly, assuming that there are 2 runways one for takeoff and one for landing.
=> Airport Simulation

c++/DP_Basics_Using_CPP/WeightedJobScheduling.cpp
Given N jobs where every job is represented by following three elements of it.
Start Time
Finish Time
Profit or Value Associated (>= 0)
Find the maximum profit subset of jobs such that no two jobs in the subset overlap.
=> Uploading Weighted Job Scheduling Solution Using DP

faceblurer.py
The program blurs out the face of people on the frame. It uses haar-cascade for detecting face and creates a heavy blur across the face.
=> Face blurer program

python/TinderBot/Bot.py, python/TinderBot/README.md
Added new feature in bot for Tinder.
=> Added screenshot feature in Tinder bot Python file

python/Prime.py, python/Sexy Prime.py
Added py file for Sexy prime numbers and prime numbers(displays all prime numbers till that number)
=> Added Sexy Prime Numbers and Prime Number

c++/Largest_Substring_between_equal_characters.cpp
Added CPP solution for the aforementioned problem.
=> Largest Substring between Equal Characters problem (Leetcode)

python/ASCII to Char.py, python/date_verifier.py
I have added date verification code using python which will return a tuple with its 0th index as True/False representing the validation of the date and 1st index as the date itself in YYYY/MM/DD format.
=> Added Date verifier using Python

c++/Repeated_DNA_sequence.cpp
Platform: Leetcode [#187](https://leetcode.com/problems/repeated-dna-sequences/).
=> Repeated DNA sequence

python/matrix_inverse.py, python/spiral_matrix.py
First Program Prints Inverse of A Square Matrix
Second Program Prints Matrix in Spiral Form
=> Python Matrix Based Solutions

c++/Power set.cpp
It is user driven code to find the power set of any given set.
=> Create Power set.cpp

c++/rootsofquadratic.cpp
Code for calculating quadratic roots in C++ Language.
**Kindly Merge my PR I have submitted this as part of HacktoberFest.** _Cheers and Thanks_
=> Code for calculating quadratic roots.

java/HeapSort.java
=> HeapSort.java

python/FlappyBirdGame.py
This is Flappy Bird Game in python.
=> FlappyBirdGame.py

java/TicTacToe.java
Added a TicTacToe game in java folder, I made this in college when I was learning java, it is made by using basic stuff like loops, switch statements and conditional statements etc, its a very beginner friendly, it helped me a lot with my learning process
=> added TicTacToe game in java

csharp/EventCenter.cs
Add csharp folder and EventCenter.cs.
=> Add EventCenter.cs

java/MinimumAddition.java
You are given an array **A[]**  of **N** positive numbers. You are also given **Q**  queries. Each query contains two integers **_l, r(l<=r)_**. For each query, determine the sum of all values that must be added to each number in range  to  such that bitwise AND of all numbers in the range is greater than 0.
You are required to minimize the total value that must be added. The value you must add to numbers is not necessarily equal for all numbers.
Note: Each query is independent of each other, that is, for each query, you must treat the range over the initial input array.
=> MinimumAddition

c++/postfix_evaluation.cpp
evaluate postfix expression using cpp.
Please accept my pr.
=> evaluation of postfix expression in cpp

c++/LRU_Cache.cpp
Used two data structure for implementing LRU Cache.
1) Queue
2) Hash
=> Implemented LRU Caching

python/Ball_fizz_buzz.py
Making boring logics interesting. Please accept this pull request.
=> Ball animation with fizz buzz logic implementation

Array/Trapping_Rain_Water.py
It is a Python Program based on Array or List in Python approach which calculates how much water can be trapped between the buildings with the most optimised approach.
=> Trapping_Rain_water.py

Javascript/Event Planner/eventplanner.html
I've added a JavaScript App "Event Planner"
* Event planner is basically a to-do like app,here you can add and remove your events.
* Simple and clean interface
* Created Using HTML5,CSS3,JavaScript
Hope you like it.
=> Added Event Planner App in Javascript

README.md
1)Readme updated with minor typo fixes from line 43 to 47
2) Added hacktoberfest link to the top of the readme file
=> Readme updated (Improving Readme #181 addressed)

Shift all 0 to left
Given an integer array, move all elements that are 0 to the left while maintaining the order of other elements in the array. The array has to be modified in-place.
=> array shifting CP

java/TravelPlannerApp.java
Travel Planner example using user input in console. Calculates budget per day, time difference and, implementing Haversine formula, calculates distande between home and destination.
=> Add TravelPlannerApp.java

python/Python Password Generator/README.md, python/Python Password Generator/generate.py, python/Scrape URLs/README.md, python/Scrape URLs/scraper.py
=> Python Password Generator

HTML5/P1.html
HTML 5 WEBPAGE WITH WORKING PROGRESSBAR
=> HTML FOR SEMI DYNAMIC WEBPAGE

pong.py
=> Pong Game Commited

c++/AnnaCafe.cpp
Link to problem- https://www.codechef.com/SNUC2020/problems/ANNACAFE
=> Solving a cpp problem using merge sort

Javascript/Flappy Bird/index.html
This PR add flappybird-like game, build using HTML canvas and javascript
=> Add flappy bird game build using HTML + JS

python/encryption.py
encryption algo for encrypting strings with blake2b and diff SHA like SHA1, SHA256 added
run python encryption.py
=> encryption algo for encrypting string with blake2b and diff SHA added

c++/Kadane's Algorithm.cpp
Kadane’s algorithm is used to find out the maximum subarray sum from an array of integers. The time complexity of the algorithm is O(n) and Space Complexity is O(1).
=> Kadane's Algorithm.cpp
